title: Quantitative Thinking
author: Dr. Christian Groll
email: groll.christian.edu@gmail.com
position: Head of Quantitative Investment Strategy
company: Scalable Capital
description: > # this means to ignore newlines until "twitter_username:"
  A blog about quantitative finance,
  data and tools.

# social links
# twitter_username: ChrisAndData
# github_username:  cgroll
# rss: rss
# youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
google_analytics: G-BZN8CJ6C41

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.md
- categories.html
- links.md
- todos.md

minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,         user_url: "https://github.com/cgroll" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/christian-groll-a4a804144/" }
    - { platform: twitter,        user_url: "https://twitter.com/ChrisAndData" }
    - { platform: youtube,        user_url: "https://www.youtube.com/christiangroll7363" }

show_excerpts: true # set to true to show excerpts on the homepage

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag